### PR TITLE
FP3: update boot.img url and checksum

### PR DESCRIPTION
**Pull request by luksus42**

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Could you please explain how this image comes to be?

**Comment by luksus42** [comment]
@peat-psuwit it is the one from the latest CI build. https://gitlab.com/ubports/community-ports/android10/fairphone/fairphone_fp3/-/pipelines/460317984

It is my way to make it "persistent" available.
(I still did not figure out, how to do it right with tags and releases to keep a version with downloadable artifacts.)

**Comment by peat-psuwit** [comment]
Doesn't the "Keep" button appear in the job page?

https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html#download-job-artifacts

**Comment by luksus42** [comment]
Oh, it does, but I did not trust it :-)
But ok, just lets try it...

**Comment by peat-psuwit** [comment]
Ok. Has the image been tested on the device?

**Comment by luksus42** [comment]
Yes sure.
I tested the image and the installer config itself on my Fairphone 3, which I am using daily.

**Comment by peat-psuwit** [comment]
Ok. Then let's get it updated.

**Pull request merged**
