### PR TITLE
Add Redmi 4X (santoni)

### PR DESCRIPTION
**Pull request by Danct12**
This PR brings Redmi 4X into the device list.

So far, no issue and everything seems to work fine (and it even installs), however need someone to help with testing userdata format as I'm currently using this device as a daily driver and cannot risk wiping my data so until that's tested, this is a draft.

### CODE REVIEW

**Comment by Flohack74** [comment]
Dont worry for userdate wipe. It is a generic thing added to the script thats executed by the recovery. Either it works or it does not work on all devices. I would therefore approve this. Do you already have a system.image channel where this device is in?

**Comment by NeoTheThird** [comment]
@Flohack74 yes, but he has an additional fastboot format that depends on it

**Comment by Flohack74** [comment]
Oh I see, well in general this is not needed. Whats the reason for it?

**Comment by NeoTheThird** [comment]
some other devices do it, too. it might be more stable than the recovery's formatting when installing from android.

**Comment by Danct12** [comment]
Just have one of my tester to try it out, and it seems to boot perfectly fine on devel.

**Pull request merged**
