### PR TITLE
yggdrasil: Add Droidian as an alternative OS

### PR DESCRIPTION
**Pull request by erikinkinen**
This downloads and installs Droidian (latest version).

### CODE REVIEW

**Comment by erikinkinen** [comment]
If this is good, should I do the same for other devices supported by Droidian (google-sargo and fxtec-pro1)?

**Comment by erikinkinen** [comment]
We are thinking about getting some new URL to pull the latest release. So, this should wait.

**Comment by Flohack74** [comment]
@erikinkinen of course you are invited to extend our installer capabilities :)

**Comment by Flohack74** [comment]
Are you still working on this, then please mark it as "WIP"...

**Comment by erikinkinen** [comment]
> Are you still working on this, then please mark it as "WIP"...

I am not woking on it anymore. Yesterday, I was because of a few issues I found. Now, I am quite sure it is working. Sorry!

**Pull request merged**
