### PR TITLE
Oneplus 2/3/3T: add/improve LineageOS/OxygenOS support

### PR DESCRIPTION
**Pull request by Vince1171**
**OnePlus 2:**
 * Use the new LineageOS plugin
 * Add OxygenOS 3.6.1 support
 
**OnePlus 3/3T:**
 * Add LineageOS support using the new plugin
 
DO NOT MERGE without #85 and ubports/ubports-installer#1834

### CODE REVIEW

**Comment by NeoTheThird** [comment]
is there a problem with opengapps? or why the removal

**Comment by Vince1171** [comment]
> is there a problem with opengapps? or why the removal

because it was a "static" install (download a specific .zip and ask the user to install it via sideload) and it's not compatible with an ORS install. I could use ORS to install a specific OpenGapps .zip too...

But I'll just finish the OpenGapps plugin and make the installation process properly ( latest version of openGapps etc... ) ^^

btw do you know if it's possible to display an option only under certain conditions? Or I just open a new feature request? ;) 
something like:
```
options:
      - var: "opengapps"
        name: "Install OpenGapps"
        type: "boolean"
        value: false
      - var: "opengappsChannel"
        name: "OpenGapps Channel"
        tooltip: "Do you want to install pico nano micro mini full version of OpenGapps?"
        link: "https://opengapps.org/"
        type: "select"
        remote_values:
          opengapps:channels:
        condition:
          var: "opengapps"
          value: true
```

**Comment by NeoTheThird** [comment]
> But I'll just finish the OpenGapps plugin and make the installation process properly ( latest version of openGapps etc... ) ^^

Ahh, ok. Great!

> btw do you know if it's possible to display an option only under certain conditions? Or I just open a new feature request? ;)

Nope, that's not a thing yet. Funny, we talked about the same thing for [postmarketos just yesterday](https://gitlab.com/postmarketOS/postmarketos/-/issues/38). Opened #87 to track this.

**Review by NeoTheThird — APPROVED** [review]
lookin' good! can be merged as soon as the plugin is live. thanks :)

**Pull request closed without merging**
