### PR TITLE
devices: drop angelica

### PR DESCRIPTION
**Pull request by muhammad23012009**
* same reason as 9A, newer devices manufactured by Xiaomi do not boot the currently released 4.9 kernel source.

### CODE REVIEW

**Comment by NotKit** [comment]
What does @erikinkinen think about this? Maybe drop UBPorts but keep Droidian?

**Comment by erikinkinen** [comment]
@FakeShell maintains the Angelica port of Droidian. AFAIK, he wants to keep maintaining it and hence only Ubuntu Touch should be dropped.

**Comment by erikinkinen** [comment]
Also, @NotKit , I do not really know the device myself, but I have heard of the lore behind this. It is a tricky device, but again the person who actually maintains the port, should comment on this, not me.

**Comment by FakeShell** [comment]
Can be dropped from ubports installer we'll hold onto it on our fork (droidian installer) for now

**Pull request merged**
