### PR TITLE
WIP: CI: fix ts-node/esm build

### PR DESCRIPTION
**Pull request by luksus42**
Trying to fix the CI build without any knowledge of node and typescript...

### CODE REVIEW

**Comment by luksus42** [comment]
So... did that work?!
@amartinz

**Comment by amartinz** [comment]
> So... did that work?! @amartinz

At least CI seems to be happy :D

But @maciek134 has more knowledge about it than me.

**Comment by luksus42** [comment]
@maciek134 any idea, how we want to proceed?

**Comment by maciek134** [comment]
Hey sorry, completely missed the email with this, I'll take a look later today.

**Comment by JamiKettunen** [comment]
@maciek134 Reminder ping, would be nice to have CI in order again so this repo isn't in limbo :)

**Comment by amartinz** [comment]
> @maciek134 Reminder ping, would be nice to have CI in order again so this repo isn't in limbo :)

Will merge tomorrow around the same time, if noone has anything against it.

**Pull request merged**
