### PR TITLE
Improve OnePlus3/3T options

### PR DESCRIPTION
**Pull request by Vince1171**
* add instruction to avoid failed installation if Android 9 was installed
* fix wipe option
* add OxygenOS 9.0.6 support

### CODE REVIEW

**Review by NeoTheThird — APPROVED** [review]
Looks v good, i'm assuming you've done all the testing, ie switching back and forth a couple times with both 3 and 3t? If so let's get this merged?

**Comment by Vince1171** [comment]
> Looks v good, i'm assuming you've done all the testing, ie switching back and forth a couple times with both 3 and 3t? If so let's get this merged?

All testing done back and forth. but only with op3T as don't have a op3. but the only difference between 3/3T in this case is the link for OxygenOS and it's the official links and md5's)
So yes, let's get this merged :D

**Comment by NeoTheThird** [comment]
alrighty, thanks again

**Comment by Vince1171** [comment]
> alrighty, thanks again

no thank YOU again for your amazing Installer :D

**Pull request merged**
