### PR TITLE
jasmine_sprout (Xiaomi Mi A2) config added

### PR DESCRIPTION
**Pull request by just-carlod**
Added config for jasmine_sprout :)

### CODE REVIEW

**Comment by just-carlod** [comment]
Is this an error? cause
> All v1 config files are translated to v2 automatically

If so how can I fix it?

**Comment by just-carlod** [comment]
nice I found an error and fix it :)

**Review by NeoTheThird — APPROVED** [review]
Looking good, thanks! Can be merged as soon as https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/merge_requests/39 is ready.

**Comment by just-carlod** [comment]
For unknown reason fastboot doesn't work on some PCs I don't know how big is scale of this problem. Installer should fail at `fastboot erase` command and user would be able to reboot device to old system. Anyway I added a warning

**Comment by NeoTheThird** [comment]
You mean fastboot format, right?

**Comment by just-carlod** [comment]
> You mean fastboot format, right?

right It's not installer or config bug. I think it's hardware issue, installer may fail on some AMD cpu's but I'm not sure if it's only AMD problem

**Pull request merged**
