### PR TITLE
Create karin.json

### PR DESCRIPTION
**Pull request by stefanomelchior**
Added Sony Xperia Z4 Tablet (SGP771, aka karin), with LTE support
On the same platform there is also karin_windy, with only wi-fi support (SGP712)

### CODE REVIEW

**Comment by NeoTheThird** [comment]
Hey, looks pretty good! Could you also add details to the [devices page](https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io)? What device id does the device report as when running android? If it's not karin, could you add it to aliases.json? You might have to create a new config for karin_windy, if everything works there as well. Also, do you know someone else who has this device and can give this config a spin to confirm everything is working? @APokorny maybe?

**Comment by stefanomelchior** [comment]
> Hey, looks pretty good! Could you also add details to the [devices page](https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io)? What device id does the device report as when running android? If it's not karin, could you add it to aliases.json? You might have to create a new config for karin_windy, if everything works there as well. Also, do you know someone else who has this device and can give this config a spin to confirm everything is working? @APokorny maybe?

@APokorny had created the porting for Sony's platform, I customized for karin (wifi+4g, this is the device I own) and somehow I suppose it works for karin_windy (wifi only) too, but I don't have a device to test it. Atm Idk anyone with the same device, but Andreas works on Z5 (dora) which belongs to the same project.
Of course I will add z4 tablet info on [devices page](https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io) as soon as I can, and info in aliases.json either

**Comment by Flohack74** [comment]
You also need to modify index.json to include the device there. Otherwise it wont list.

**Comment by mariogrip** [comment]
Also have you tried this config? using `ubports-installer -f [config]`

**Review by mariogrip — APPROVED** [review]
If this has been tested, LGTM :+1:

**Pull request merged**
