### PR TITLE
v2: devices: cheeseburger, dumpling: remove useless twrp step, clean up

### PR DESCRIPTION
**Pull request by maciek134**
Tested on a fresh 5t after unlocking the bootloader.

### CODE REVIEW

**Comment by maciek134** [comment]
And now I even used the file for 5t instead of 5 :sweat_smile:

**Comment by amartinz** [comment]
Are you sure the device works with any firmware and does not require a specific state?

**Comment by maciek134** [comment]
As sure as I can be, I installed from stock OOS 10.0.1 (the device still had a locked bootloader when I got it). And at first I flashed `cheeseburger` which surprisingly mostly worked, save for the fingerprint reader. All sensors work, camera works, cellular works too (data, sms and calls on both slots).

**Review by amartinz — APPROVED** [review]

**Comment by maciek134** [comment]
Well we recommend flashing 10.0.1 before starting the installation :D this is mainly motivated by issues in the Welcome group on Telegram, where we recommended not doing the TWRP or firmware steps anyway.

**Pull request merged**
