### PR TITLE
devices: add support for SHIFT SHIFT6mq (axolotl)

### PR DESCRIPTION
**Pull request by amartinz**
This adds the config file for SHIFT6mq (axolotl) and also adds `f2fs` as supported partition type (which is used by axolotl).

### CODE REVIEW

**Comment by NeoTheThird** [comment]
any news here? @Flohack74 @amartinz

**Comment by amartinz** [comment]
Not yet, unfortunately.

The SHIFT6mq is running Halium 10 and has dynamic partitions.
We need to patch the recovery and install scripts before we can properly support it in the installer.

**Comment by Flohack74** [comment]
I will go to review stuff now that cpusets is solved @amartinz

**Comment by amartinz** [comment]
Pending: another update to the recovery to enable ADB by default.

Currently the workflow is not working for users:

1) Enter recovery
2) It looks for adb devices

This will fail, because you need to enable ADB inside the recovery on newer halium versions (for security reasons) via navigating inside the recovery to `Advanced` -> `Enable ADB`.

However this step is not shown in UI.

Also the current halium-10.0 builds are broken and need to be rebuilt to be fixed.

**Comment by amartinz** [comment]
https://ubports.open-cuts.org/run/6228a0fb8b04550008490150

**Comment by amartinz** [comment]
Alright, so this is a huge rework and depends on https://github.com/ubports/ubports-installer/pull/2492

**Comment by amartinz** [comment]
Installer changed have landed, so this should be good to go once a new version of the installer gets released :)

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
